Background color changer project PR from branch
Tenet-Coding/Hacktoberfest-Projects pull request #26
Opened 2021-09-30 04:58 UTC by BajraYeJoon

2021-09-30 05:56 UTC, Harshil-Jani reviewed
Looks Good to me :100:

2021-09-30 05:57 UTC, Harshil-Jani commented
We will merge it from tomorrow.. @BajraYeJoon Let Hacktoberfest begun ! :tada:

2021-09-30 06:11 UTC, soumik2012 commented on Background Color Changer/index.html
> +<!DOCTYPE html>
- Write a folder name  `Background_Color_Changer` not this `Background Color Changer`

2021-09-30 06:22 UTC, soumik2012 requested changes
Add Readme.md File of Background Color it should be contained 
- Name of Project
- Demo of Project in .gif how your project is look 
- Description of project 
-  Requirements or Setup instructions
-  Name of Author(s)  
- [Look Here](https://github.com/Tenet-Coding/Hacktoberfest-Projects/blob/master/ConwaysGameOfLife/README.md)

2021-09-30 20:04 UTC, BajraYeJoon commented
All Changes requested are commited

2021-10-01 08:00 UTC, Harshil-Jani commented
@BajraYeJoon Just add the .gif for your working project int README.md and then we are good to go :star2:

2021-10-01 08:39 UTC, BajraYeJoon commented
Readme.md is updated with requested changes

2021-10-01 09:19 UTC, soumik2012 approved these changes
LGTM 💯

2021-10-01 10:05 UTC, Harshil-Jani reviewed
We are good to go :tada:

2021-10-01 10:06 UTC, Harshil-Jani approved these changes

2021-10-01 16:13 UTC, merged

2021-10-01 16:14 UTC, soumik2012 commented
@BajraYeJoon It will be showing now 
Thank you for contributing to @tenet-coding 🥳 🍾