7suyash7 notes app
Tenet-Coding/Hacktoberfest-Projects pull request #36
Opened 2021-10-01 06:24 UTC by 7suyash7

## Description

Created a NotesApp with LocalStorage as well as Search Functionality to search for your notes even if they are Thousands of them.

## Add GIF/ScreenShot 
![NotesApp - Copy](https://user-images.githubusercontent.com/89125422/135574863-c10d3b64-6d7e-4719-a9da-34fdd69e69e3.PNG)

## Task Checklist
Put x in between the square brackets without any spaces to tick your Task.  Create a PR only after you complete all the tasks.
- [x] You have created a new branch for contribution.
- [x] Added README.md for your project in a specified folder.
- [x] Add Demo in GIF or Screenshot form.
- [x] You are Registered Officially for HacktoberFest 2021 as Partcipant.
- [x] Followed Contribution Guidelines.

2021-10-01 08:18 UTC, Harshil-Jani commented
@7suyash7 
Update your Readme file 
- Project Name
- Short Description
- .gif of working project.
- Author name 

And we are good to go ! :star2:

2021-10-01 08:29 UTC, soumik2012 requested changes
Readme.md File should be contained 
- Name of Project
- Demo of Project in .gif how your project is look 
- Description of project 
-  Requirements or Setup instructions
-  Name of Author(s)  
- [Look Here](https://github.com/Tenet-Coding/Hacktoberfest-Projects/blob/master/ConwaysGameOfLife/README.md)

2021-10-01 10:35 UTC, 7suyash7 commented
readme.md has been updated @Harshil-Jani please check it once!

2021-10-01 19:56 UTC, Harshil-Jani commented
@7suyash7 You have deleted your Readme file ! We can't see it. Add it again so that we can merge your work.

2021-10-02 06:07 UTC, 7suyash7 commented
added the readme file again pls check.

2021-10-03 12:50 UTC, Harshil-Jani requested changes

2021-10-03 12:50 UTC, Harshil-Jani commented on NotesApp(7suyash7)/index.html
> +</html>
New line at the end of file.

2021-10-03 12:50 UTC, Harshil-Jani commented on NotesApp(7suyash7)/script.js
> +})
New line at the end of file

2021-10-03 13:42 UTC, soumik2012 requested changes
Make the changes then we are good to go

2021-10-05 06:54 UTC, Harshil-Jani approved these changes

2021-10-05 06:54 UTC, merged