Memory Game
Tenet-Coding/Hacktoberfest-Projects pull request #41
Opened 2021-10-01 10:05 UTC by 2devyank

## Description

- Its a memory game which will test your memory

Closes #28 

## Add GIF/ScreenShot 
![Untitled design (1)](https://user-images.githubusercontent.com/78840243/135575411-3171de1d-4b36-4d80-97d6-8f4ca9e5aab7.gif)

## Task Checklist
Put x in between the square brackets without any spaces to tick your Task.  Create a PR only after you complete all the tasks.
- [x] You have created a new branch for contribution.
- [x] Added README.md for your project in a specified folder.
- [x] Add Demo in GIF or Screenshot form.
- [x] You are Registered Officially for HacktoberFest 2021 as Partcipant.
- [x] Followed Contribution Guidelines.

## Issue 
 your issue no. #28

2021-10-01 10:08 UTC, 2devyank commented
@soumik2012 @Harshil-Jani I think now everything is fine please check. Sorry for the inconvenience.

2021-10-01 10:44 UTC, Harshil-Jani approved these changes
We are good to go :rocket:

2021-10-01 11:35 UTC, soumik2012 requested changes
Code is fine to add your author name in the readme.md file

2021-10-01 11:35 UTC, soumik2012 commented on MemoryGame/README.md
> +![Untitled design (1)](https://user-images.githubusercontent.com/78840243/135575411-3171de1d-4b36-4d80-97d6-8f4ca9e5aab7.gif)
Write your author-name in readme.md

2021-10-01 13:34 UTC, 2devyank commented
@soumik2012 I have added please check

2021-10-02 03:41 UTC, soumik2012 approved these changes
LGTM 💯

2021-10-02 03:42 UTC, merged