Notepad siddhantkhariwal
Tenet-Coding/Hacktoberfest-Projects pull request #43
Opened 2021-10-01 10:28 UTC by siddhantkhariwal

## Description

- Notepad app made with vanilla, HTML, CSS, and bootstrap.
Closes #27 

## Add GIF/ScreenShot 

- https://i.imgur.com/4GEkv2P.gifv

## Task Checklist
Put x in between the square brackets without any spaces to tick your Task.  Create a PR only after you complete all the tasks.
- [x ] You have created a new branch for contribution.
- [ x] Added README.md for your project in a specified folder.
- [ x] Add Demo in GIF or Screenshot form.
- [ x] You are Registered Officially for HacktoberFest 2021 as Partcipant.
- [ x] Followed Contribution Guidelines.

## Issue 
27

2021-10-01 12:20 UTC, Harshil-Jani requested changes
Update README as per contribution guidelines.

2021-10-01 12:20 UTC, Harshil-Jani commented on Notepad-siddhantkhariwal/Readme.md
> +*********Notepad***********
Update Readme as per contribution guidelines :
- Name of Project
- Demo of Project in .gif how your project is look 
- Description of project 
-  Requirements or Setup instructions
-  Name of Author(s)  
- [Demo Readme](https://github.com/Tenet-Coding/Hacktoberfest-Projects/blob/master/ConwaysGameOfLife/README.md)

2021-10-01 15:49 UTC, siddhantkhariwal commented
> Update README as per contribution guidelines.

Hey, @Harshil-Jani I completed the readme file. please see through it.

2021-10-02 03:58 UTC, soumik2012 approved these changes
Nicely done @siddhantkhariwal

2021-10-03 03:16 UTC, merged