Ping pong game coderchirag
Tenet-Coding/Hacktoberfest-Projects pull request #46
Opened 2021-10-01 15:47 UTC by CoderChirag

2021-10-01 15:49 UTC, CoderChirag commented
Now check the game, I have created a new branch. And if you find it good then merge please

2021-10-01 17:16 UTC, Harshil-Jani commented
@CoderChirag 
Add Readme file in your Project Folder and include following details.
- Project Name
- Short Description
- .gif of working project.
- Author name 

And we are good to go ! :star2:

2021-10-01 17:38 UTC, CoderChirag commented
Added the readme file also. Now check and merge please

2021-10-02 05:19 UTC, soumik2012 requested changes
The response time of the ball is very slow Fixed it ...

2021-10-02 05:19 UTC, soumik2012 commented on ping-pong game/index.html
> +</html>
Add a new line at the EOF.

2021-10-02 05:19 UTC, soumik2012 commented on ping-pong game/index.js
> +});
Add a new line at the EOF.

2021-10-02 05:19 UTC, soumik2012 commented on ping-pong game/style.css
> +}
Add a new line at the EOF.

2021-10-02 12:57 UTC, CoderChirag commented
@Harshil-Jani bro, Now if this project is okk, then please merge it

2021-10-03 03:14 UTC, soumik2012 commented
@CoderChirag where are your files???

2021-10-03 09:34 UTC, CoderChirag commented
@soumik2012  see the **Files changed** tab above. There you would find all the files.

2021-10-03 09:34 UTC, CoderChirag commented
@Harshil-Jani bro when would you merge it bro? Is there any mistake left now?

2021-10-03 12:53 UTC, Harshil-Jani commented on ping-pong game/index.html
> +</html>
Create a new line at end of file

2021-10-03 12:53 UTC, Harshil-Jani commented on ping-pong game/index.js
> +});
Create a new line at end of file

2021-10-03 12:53 UTC, Harshil-Jani commented on ping-pong game/style.css
> +}
Create a new line at end of file

2021-10-03 12:54 UTC, Harshil-Jani commented
@CoderChirag Just create new lines wherever asked and then we can merge it !

2021-10-03 17:17 UTC, CoderChirag commented
@Harshil-Jani  bro done. Now merge it please

2021-10-05 06:55 UTC, Harshil-Jani approved these changes

2021-10-05 06:56 UTC, merged