Added roman-numeral-converter by h2o-Noob
Tenet-Coding/Hacktoberfest-Projects pull request #68
Opened 2021-10-04 03:19 UTC by h2o-Noob

## Description

- My web-app converts any number from 1 to 999,999,999 to its roman-numeral form. I didn't used any maths library or api request. Whole algo was written using pure vanilla-js.

## Add GIF/ScreenShot 

- https://drive.google.com/file/d/11z3qHQKAJXS0QJz5AZmVYc_MweZ64_gG/view?usp=sharing

## Task Checklist
Put x in between the square brackets without any spaces to tick your Task.  Create a PR only after you complete all the tasks.
- [x] You have created a new branch for contribution.
- [x] Added README.md for your project in a specified folder.
- [x] Add Demo in GIF or Screenshot form.
- [x] You are Registered Officially for HacktoberFest 2021 as Partcipant.
- [x] Followed Contribution Guidelines.

## Issue 
Mention your issue no.
64

2021-10-04 14:10 UTC, h2o-Noob commented
@Harshil-Jani sir I created a separate branch now, please merge my request :)

2021-10-05 06:08 UTC, soumik2012 requested changes
Everything is nice but some minnor changes are needed

2021-10-05 06:08 UTC, soumik2012 commented on romanNumeralConverter_h2o-Noob/index.html
> +</html>
Add new line at EOF

2021-10-05 06:08 UTC, soumik2012 commented on romanNumeralConverter_h2o-Noob/readme.txt
> +
Add picture of project in gif

2021-10-05 06:08 UTC, soumik2012 commented on romanNumeralConverter_h2o-Noob/romCon.css
> +}
Add new line at EOF

2021-10-05 06:08 UTC, soumik2012 commented on romanNumeralConverter_h2o-Noob/style.css
> +}
Add new at line at EOF

2021-10-06 05:22 UTC, h2o-Noob commented
> Everything is nice but some minnor changes are needed  

Sir now please merge my pr

2021-10-06 09:54 UTC, merged